run:
  # timeout for analysis, e.g. 30s, 3m, default is 1m
  timeout: 5m

linters:
  disable-all: true
  enable:
    # --- Core & Bug Detection ---
    - govet
    - staticcheck
    - errcheck
    - gosec
    - copyloopvar    # Replaces exportloopref. Ensures loop variables are copied correctly in closures.
    - nilerr         # Checks for `return nil, err` where `err` is not nil.

    # --- Style, Formatting & Complexity ---
    - gofumpt        # A stricter gofmt/goimports. Enforces more consistent style.
    - goimports
    - goconst
    - misspell
    - tagliatelle
    - unconvert
    - gocognit       # Checks cognitive complexity of functions.
    - nolintlint     # Linter for `//nolint` comments.

    # --- Performance & Optimization ---
    - prealloc
    - ineffassign
    - bodyclose
    - makezero       # Finds `make([]T, N)` that should be `make([]T, 0, N)`.

    # --- Other ---
    - unparam

linters-settings:
  # gofumpt includes the functionality of goimports.
  goimports:
    local-prefixes: github.com/arwoosa/vulpes
  misspell:
    locale: US
  errcheck:
    check-type-assertions: true
  tagliatelle:
    case:
      rules:
        json: snake
        yaml: snake
  goconst:
    # Make goconst more sensitive.
    min-len: 2
    min-occurrences: 2
  unparam:
    # Don't report unused parameters in exported functions.
    check-exported: false
  nolintlint:
    # Require a reason for disabling a linter.
    require-explanation: true
    # Require the linter name to be specified.
    require-specific: true

issues:
  # No limit on issues from a single linter or of the same type.
  max-same-issues: 0
  max-issues-per-linter: 0

  # We are using disable-all, so we don't need to exclude defaults.
  exclude-use-default: false

  exclude-rules:
    # In tests, it's common to not check errors directly, but use helper functions.
    - path: _test\.go
      linters:
        - errcheck

    # In tests, using weak random numbers is acceptable.
    - path: _test\.go
      text: "G404: Use of weak random number generator"
      linters:
        - gosec

  exclude:
    # This is correct. Exclude gosec's G104 because errcheck handles it better.
    - "G104"
