name: "partivo_form_service"
mode: "dev"
port: 8081
version: 1.0.0
time_zone: "Asia/Taipei"
log:
  level: "debug"

mongodb:
  host: "127.0.0.1"
  port: 27017
  db: "partivo"

keto:
  write_addr: "192.168.1.123:4467"
  read_addr: "192.168.1.123:4466"

# external:
#   order_service:
#     endpoint: "192.168.1.122:8081"
#     timeout: "10s"

pagination:
  default_page_size: 1000
  max_page_size: 2000

business_rules:
  max_templates_per_merchant: 3






