name: "partivo_form_service"
mode: "dev"
port: 8081
time_zone: "UTC"
log:
  level: "debug"
  
mongodb:
  host: "host.docker.internal"
  port: 27017
  db: "partivo"

keto:
  write_addr: "192.168.1.123:4467"
  read_addr: "192.168.1.123:4466"

pagination:
  default_page_size: 20
  max_page_size: 100

business_rules:
  max_templates_per_merchant: 3






