name: "partivo_form_service"
mode: "dev"
port: 8081
time_zone: "UTC"
log:
  level: "debug"

mongodb:
  host: "127.0.0.1"
  port: 27017
  db: "partivo"

keto:
  write_addr: "172.20.0.22:4467"
  read_addr: "172.20.0.22:4466"

pagination:
  default_page_size: 1000
  max_page_size: 2000

business_rules:
  max_templates_per_merchant: 3






